# Testing ```position_mask = packing_mask.all(1).all(1)```

In [14]:
import numpy as np
import torch

x = torch.tensor([[
                    [
                      [[ True,   False],
                      [ True,   True]],

                      [[ False,  False],
                        [ True,   False]],

                      [[ True,   False],
                        [ True,   True]],

                      [[ True,   False],
                        [ True,   True]],

                      [[ True,   False],
                        [ True,   True]],

                      [[ True,   False],
                        [ True,   True]]
                    ],

                    [
                      [[ True,   False],
                        [ True,   True]],

                      [[ True,   False],
                        [ True,   True]],

                      [[ True,   False],
                        [ True,   True]],

                      [[ True,   False],
                        [ True,   True]],

                      [[ True,   False],
                        [ True,   True]],

                        [[ True,   False],
                        [ True,   True]]
                      ]
                  ]])

print(f"Shape of x: {x.shape}")

x_flat = x.flatten(3, 4)
print(f"\n\nFlattened:\n{x_flat}\n")
print(f"Shape of x_flat: {x_flat.shape}")

x_all = x_flat.all(1)
print(f"\n\nx.all(1):\n{x_all}\n")
print(f"Shape of x_all: {x_all.shape}")


x_all_all = x_flat.all(1).all(1)
print(f"\n\nx.all(1).all(1):\n{x_all_all}\n")
print(f"Shape of x_all_all: {x_all_all.shape}")

x_premuted = x_flat.permute(0, 3, 1, 2)
print(f"\n\nx_flat.permuted\n{x_premuted}\n")
print(f"Shape of x_flat.permuted: {x_premuted.shape}")


Shape of x: torch.Size([1, 2, 6, 2, 2])


Flattened:
tensor([[[[ True, False,  True,  True],
          [False, False,  True, False],
          [ True, False,  True,  True],
          [ True, False,  True,  True],
          [ True, False,  True,  True],
          [ True, False,  True,  True]],

         [[ True, False,  True,  True],
          [ True, False,  True,  True],
          [ True, False,  True,  True],
          [ True, False,  True,  True],
          [ True, False,  True,  True],
          [ True, False,  True,  True]]]])

Shape of x_flat: torch.Size([1, 2, 6, 4])


x.all(1):
tensor([[[ True, False,  True,  True],
         [False, False,  True, False],
         [ True, False,  True,  True],
         [ True, False,  True,  True],
         [ True, False,  True,  True],
         [ True, False,  True,  True]]])

Shape of x_all: torch.Size([1, 6, 4])


x.all(1).all(1):
tensor([[False, False,  True, False]])

Shape of x_all_all: torch.Size([1, 4])


x_flat.permuted
tensor([[[[ True

In [2]:
import torch

def binary_encoder(x, binary_dim):
    # x: size x 1
    if binary_dim == 1:
        x_encoding = x
    else:
        binary_list = []
        divide = x
        for i in range(binary_dim):
            binary = divide % 2
            binary_list.insert(0,binary)
            divide = torch.div(divide,2,rounding_mode='trunc')

        x_encoding = torch.stack(binary_list,-1).flatten(-2,-1)
    return x_encoding

x = torch.tensor(
    [[[-1.9651,  6.1738, -1.0707, 2.3734, -2.0688,  0.9693],
      [-0.9256,  5.0226, -0.4454, 2.8044, -2.2230,  0.9239],
      [-0.0772,  5.0069,  0.9721, 3.5038, -1.5165,  1.0996],
      [-3.5112,  2.2332, -3.3826, 0.6964, -0.9044,  1.6625],
      [-2.2385,  2.2095, -1.2564, 1.7455,  0.1554,  1.9261],
      [-1.6245,  2.2948, -1.3191, 1.1467,  0.0973,  1.7528]]],
    dtype=torch.float32
)
binary_encoder(x, 8)

tensor([[[-0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, 0.0349,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 1.0000, 0.1738,
          -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, 0.9293,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.3734,
          -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, 1.0000, 1.9312,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.9693],
         [-0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, 1.0744,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 1.0226,
          -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, 1.5546,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.8044,
          -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, 1.0000, 1.7770,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.9239],
         [-0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.000