# Testing ```position_mask = packing_mask.all(1).all(1)```

In [14]:
import numpy as np
import torch

x = torch.tensor([[
                    [
                      [[ True,   False],
                      [ True,   True]],

                      [[ False,  False],
                        [ True,   False]],

                      [[ True,   False],
                        [ True,   True]],

                      [[ True,   False],
                        [ True,   True]],

                      [[ True,   False],
                        [ True,   True]],

                      [[ True,   False],
                        [ True,   True]]
                    ],

                    [
                      [[ True,   False],
                        [ True,   True]],

                      [[ True,   False],
                        [ True,   True]],

                      [[ True,   False],
                        [ True,   True]],

                      [[ True,   False],
                        [ True,   True]],

                      [[ True,   False],
                        [ True,   True]],

                        [[ True,   False],
                        [ True,   True]]
                      ]
                  ]])

print(f"Shape of x: {x.shape}")

x_flat = x.flatten(3, 4)
print(f"\n\nFlattened:\n{x_flat}\n")
print(f"Shape of x_flat: {x_flat.shape}")

x_all = x_flat.all(1)
print(f"\n\nx.all(1):\n{x_all}\n")
print(f"Shape of x_all: {x_all.shape}")


x_all_all = x_flat.all(1).all(1)
print(f"\n\nx.all(1).all(1):\n{x_all_all}\n")
print(f"Shape of x_all_all: {x_all_all.shape}")

x_premuted = x_flat.permute(0, 3, 1, 2)
print(f"\n\nx_flat.permuted\n{x_premuted}\n")
print(f"Shape of x_flat.permuted: {x_premuted.shape}")


Shape of x: torch.Size([1, 2, 6, 2, 2])


Flattened:
tensor([[[[ True, False,  True,  True],
          [False, False,  True, False],
          [ True, False,  True,  True],
          [ True, False,  True,  True],
          [ True, False,  True,  True],
          [ True, False,  True,  True]],

         [[ True, False,  True,  True],
          [ True, False,  True,  True],
          [ True, False,  True,  True],
          [ True, False,  True,  True],
          [ True, False,  True,  True],
          [ True, False,  True,  True]]]])

Shape of x_flat: torch.Size([1, 2, 6, 4])


x.all(1):
tensor([[[ True, False,  True,  True],
         [False, False,  True, False],
         [ True, False,  True,  True],
         [ True, False,  True,  True],
         [ True, False,  True,  True],
         [ True, False,  True,  True]]])

Shape of x_all: torch.Size([1, 6, 4])


x.all(1).all(1):
tensor([[False, False,  True, False]])

Shape of x_all_all: torch.Size([1, 4])


x_flat.permuted
tensor([[[[ True